const FLIGHT_STATUS = {
  FLIGHT_AVAILABLE: 'FLIGHT_AVAILABLE',
  FLIGHT_UNAVAILABLE: 'FLIGHT_UNAVAILABLE',
  FLIGHT_SOLDOUT: 'FLIGHT_SOLDOUT',
  MESSAGE: {
    FLIGHT_AVAILABLE: '随心飞有票!!!',
    FLIGHT_UNAVAILABLE: '机票有票, 但是随心飞卖完了',
    FLIGHT_SOLDOUT: '机票卖完了',
  },
};

module.exports = FLIGHT_STATUS;
